# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
confirm_os_window_close 0 

# Theme
#include themes/catppuccin/mocha.conf
# include themes/rose-pine/rose-pine.conf
# include themes/gruvbox/gruvbox_dark.conf

# END_KITTY_THEME
background_opacity 0.7 
# background_opacity 1
dynamic_background_opacity yes

cursor_shape beam
cursor_beam_thickness 2
font_size 14.0
window_padding_width 25
font_family     JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
cursor_trail 1

# vim:ft=kitty
allow_remote_control yes
listen_on unix:/tmp/kitty-socket

# Include Pywal-generated colors
include ~/.cache/wal/colors-kitty.conf
