# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FAEED6
background         #171819
cursor             #A2A19E

active_tab_foreground     #171819
active_tab_background     #FAEED6
inactive_tab_foreground   #FAEED6
inactive_tab_background   #171819

active_border_color   #FAEED6
inactive_border_color #171819
bell_border_color     #101216

color0      #3E3F40
color1		#101216
color2		#373F4C
color3		#A8474C
color4		#589576
color5		#888E97
color6		#B59B67
color7		#F0DFBC
color8		#A89C84
color9		#15181D
color10		#4A5465
color11		#E05F65
color12		#76C79D
color13		#B5BDC9
color14		#F1CF8A
color15		#F0DFBC
